apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: users
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: users-config
          - secretRef:
              name:  users-secret
            
